[package]
name = "block"
version = "0.1.0"
authors = ["nabil-otsmane <hn_otsmane@esi.dz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
